### ISSUE TITLE
Summarize free space at the end of the .map file

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1046]
Currently the .map file ends with a summary of used space by section type:

```
USED:
    ROM0: $3fa0 bytes in 1 bank
    ROMX: $1db849 bytes in 119 banks
    SRAM: $78d8 bytes in 4 banks
    WRAM0: $0fda bytes in 1 bank
    WRAMX: $5b6b bytes in 7 banks
    HRAM: $0070 bytes in 1 bank
```

It could be useful to summarize free space as well, at least in the used banks, since it's nontrivial to calculate by checking the size of each type of bank.

For example:

```
USED:
    ROM0: $3fa0 bytes in 1 bank ($0060 free)
    ROMX: $1db849 bytes in 119 banks ($07b7 free)
    SRAM: $78d8 bytes in 4 banks ($0728 free)
    WRAM0: $0fda bytes in 1 bank ($0026 free)
    WRAMX: $5b6b bytes in 7 banks ($1495 free)
    HRAM: $0070 bytes in 1 bank ($000f free)
```

(This cannot take unused banks into account because rgblink doesn't know what MBC the ROM will ultimately use or how many total banks there will be.)

**Comment by ISSOtm** [comment]
I would rather put the "free" info before the bank counts, so that it's clearer that empty trailing banks are not considered.

**Comment by Rangi42** [comment]
> I would rather put the "free" info before the bank counts, so that it's clearer that empty trailing banks are not considered.

In that case "SPACE" might be more appropriate than "USED".

```
SPACE:
    ROM0: $0060 free (used $3fa0 bytes in 1 bank)
    ROMX: $07b7 free (used $1db849 bytes in 119 banks)
    SRAM: $0728 free (used $78d8 bytes in 4 banks)
    WRAM0: $0026 free (used $0fda bytes in 1 bank)
    WRAMX: $1495 free (used $5b6b bytes in 7 banks)
    HRAM: $000f free (used $0070 bytes in 1 bank)
```

**Comment by ISSOtm** [comment]
Or "MEMORY USAGE", or "SUMMARY"?

```
SUMMARY:
    ROM0:   $3fa0 bytes used / $0060 free
    ROMX: $1db849 bytes used / $07b7 free in 119 banks
...
```
