### ISSUE TITLE
[Feature request] Report slack totals at the end of the .map file

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#777]
For example:

```
FREE:
    ROM0: $0000 bytes
    ROMX: $0000 bytes
    WRAM0: $0000 bytes
    WRAMX: $0000 bytes
    HRAM: $0000 bytes
```

This would just sum up the `SLACK` values for each bank category, counting `EMPTY` banks as being entirely slack.
